export type { ActionIntroSlideProps, IntroSlideProps, HierarchySlideProps, ComparisonSlideProps, SummarySlideProps, PracticeSummarySlideProps } from './AllSlides';
export {
  ActionIntroSlide,
  IntroSlide,
  ModuleIntroSlide,
  ContentBlockSlide,
  SectionBreakSlide,
  WarmUpQuizSlide,
  GlossarySlide,
  DefinitionsSlide,
  DiModalitiesSlide,
  PieChartSlide,
  AiWorkflowSlide,
  PromptTypesSlide,
  PromptTechniquesSlide,
  WorkflowSummarySlide,
  PromptTemplateSlide,
  TransitionSlide,
  HierarchySlide,
  MetaBlockSlide,
  InputBlockSlide,
  OutputBlockSlide,
  ReasoningModelsSlide,
  ReasoningBlockSlide,
  QualityBlockSlide,
  AdvancedBlockSlide,
  AdvancedParameters2Slide,
  FullExampleSlide,
  ComparisonSlide,
  SummarySlide,
  TestIntroSlide,
  TestSectionSlide,
  TestResultsSlide,
  PracticeIntroSlide,
  PracticeScenarioSlide,
  ProductivityInfographicSlide,
  PracticeSummarySlide,
} from './AllSlides';
